import type { Metadata } from "next";
import "@/styles/globals.css";
import DashboardWrapper from "./dashboardWrapper";
import { dmSans } from "./font";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body className="font-sans">
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
